### ISSUE TITLE
Crashes on InternetExplorer11 and Safari5.x (MacOS /iOS)

### ISSUE THREAD

**Issue by fontanon** [andalugeeks/andaluh-www#16]
On Internet Explorer 11 (Windows 10) and Safari5.x the app does not transcribe. You can type on the left side, but nothing happens on the right side (spanish to andaluh).

Opening the inspector, the following errors are revealed.

**Internet Explorer 11**

Snapshot: https://drive.google.com/file/d/1jaQgHRBATlQ9vY2sRbEX-jfZnbUcNDh2/view?usp=sharing

Traceback:

```
ERROR SyntaxError: Cuantificador inesperado
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Cuantificador inesperado",
      message: "Cuantificador inesperado",
      name: "SyntaxError",
      number: -2146823270,
      stack: "SyntaxError: Cuantificador inesperado
   at s (https://andaluh.es/transcriptor/polyfills.fa2db1f903cb8e071f2e.js:1:67896)
   at W (https://andaluh.es/transcriptor/main.4a268ab084f37444796c.js:1:137626)
   at h_rules (https://andaluh.es/transcriptor/main.4a268ab084f37444796c.js:1:120404)
   at Anonymous function (https://andaluh.es/transcriptor/main.4a268ab084f37444796c.js:1:127291)
   at transcript (https://andaluh.es/transcriptor/main.4a268ab084f37444796c.js:1:127077)
   at Anonymous function (https://andaluh.es/transcriptor/main.4a268ab084f37444796c.js:1:1120606)
   at t.prototype.__tryOrUnsub (https://andaluh.es/transcriptor/main.4a268ab084f37444796c.js:1:192017)
   at t.prototype.next (https://andaluh.es/transcriptor/main.4a268ab084f37444796c.js:1:191183)
   at t.prototype._next (https://andaluh.es/transcriptor/main.4a268ab084f37444796c.js:1:190275)
   at t.prototype.next (https://andaluh.es/transcriptor/main.4a268ab084f37444796c.js:1:189958)",
      Symbol()_h.umo0vsbss9t: undefined,
      Symbol()_i.umo0vsbss9t: undefined,
      Symbol(rxSubscriber)_g.umo0vsbss9t: undefined
   }
```

**Safari**

Snapshot: https://drive.google.com/file/d/1lb6XZO49ETmM946Q8F8yaGFYDviHb3fl/view?usp=sharing

Traceback:

```
EROR
  Error
    line: 1
    message: "Invalid regular expression: unrecognized character after (?"
    sourceId: 2072801568
    sourceURL: "https://andaluh.es/transcriptor/polyfills.fa2db1f903cb8e071f2e.js"
```

**Could it be Typescript and XREGEXP?**

I'd suspect this is related with `typescript` compilation to javascript. Because when running a dev server (with `ng serve`), the errors looks related with bad syntax on `xregexp` source code functions: 

https://drive.google.com/file/d/1K4d70SjWvVY2UMLAu-DiFIAvGdK-GIx7/view?usp=sharing

**Comment by fontanon** [comment]
After 1.5month since migration to andaluh-js 1.1.8 (which removed the XREGEXP dependency) we can tell this bug if closed! All users reported the fix :)
